repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Rust formatting
        description: Format Rust code with rustfmt
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: clippy
        name: Rust linting
        description: Lint Rust code with clippy
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        args: ["--all-targets", "--all-features", "--", "-D", "unused-imports", "-D", "clippy::collapsible_else_if", "-D", "clippy::int_plus_one"]

  - repo: local
    hooks:
      - id: cargo-check
        name: Cargo check
        description: Check if Rust code compiles
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: Cargo test
        description: Run Rust tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false